In [169]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings('ignore')

In [170]:
df = pd.read_csv('earthquake_data.csv')

In [171]:
df

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,green,1,768,us,117,0.509,17.0,mww,14.000,-9.7963,159.596,"Malango, Solomon Islands",Oceania,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,18-11-2022 13:37,4,4,green,0,735,us,99,2.229,34.0,mww,25.000,-4.9559,100.738,"Bengkulu, Indonesia",NaN,NaN
2,M 7.0 -,7.0,12-11-2022 07:09,3,3,green,1,755,us,147,3.125,18.0,mww,579.000,-20.0508,-178.346,NaN,Oceania,Fiji
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,11-11-2022 10:48,5,5,green,1,833,us,149,1.865,21.0,mww,37.000,-19.2918,-172.129,"Neiafu, Tonga",NaN,NaN
4,M 6.6 -,6.6,09-11-2022 10:14,0,2,green,1,670,us,131,4.998,27.0,mww,624.464,-25.5948,178.278,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,"M 7.7 - 28 km SSW of Puerto El Triunfo, El Sal...",7.7,13-01-2001 17:33,0,8,NaN,0,912,us,427,0.000,0.0,mwc,60.000,13.0490,-88.660,"Puerto El Triunfo, El Salvador",NaN,NaN
778,"M 6.9 - 47 km S of Old Harbor, Alaska",6.9,10-01-2001 16:02,5,7,NaN,0,745,ak,0,0.000,0.0,mw,36.400,56.7744,-153.281,"Old Harbor, Alaska",North America,NaN
779,"M 7.1 - 16 km NE of Port-Olry, Vanuatu",7.1,09-01-2001 16:49,0,7,NaN,0,776,us,372,0.000,0.0,mwb,103.000,-14.9280,167.170,"Port-Olry, Vanuatu",NaN,Vanuatu
780,"M 6.8 - Mindanao, Philippines",6.8,01-01-2001 08:54,0,5,NaN,0,711,us,64,0.000,0.0,mwc,33.000,6.6310,126.899,"Mindanao, Philippines",NaN,NaN
781,"M 7.5 - 21 km SE of Lukatan, Philippines",7.5,01-01-2001 06:57,0,7,NaN,0,865,us,324,0.000,0.0,mwc,33.000,6.8980,126.579,"Lukatan, Philippines",NaN,Philippines

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      782 non-null    object
 1   magnitude  782 non-null    float64
 2   date_time  782 non-null    object
 3   cdi        782 non-null    int64
 4   mmi        782 non-null    int64
 5   alert      415 non-null    object
 6   tsunami    782 non-null    int64
 7   sig        782 non-null    int64
 8   net        782 non-null    object
 9   nst        782 non-null    int64
 10  dmin       782 non-null    float64
 11  gap        782 non-null    float64
 12  magType    782 non-null    object
 13  depth      782 non-null    float64
 14  latitude   782 non-null    float64
 15  longitude  782 non-null    float64
 16  location   777 non-null    object
 17  continent  206 non-null    object
 18  country    484 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 116.2+ KB

In [173]:
df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,green,1,768,us,117,0.509,17.0,mww,14.000,-9.7963,159.596,"Malango, Solomon Islands",Oceania,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,18-11-2022 13:37,4,4,green,0,735,us,99,2.229,34.0,mww,25.000,-4.9559,100.738,"Bengkulu, Indonesia",NaN,NaN
2,M 7.0 -,7.0,12-11-2022 07:09,3,3,green,1,755,us,147,3.125,18.0,mww,579.000,-20.0508,-178.346,NaN,Oceania,Fiji
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,11-11-2022 10:48,5,5,green,1,833,us,149,1.865,21.0,mww,37.000,-19.2918,-172.129,"Neiafu, Tonga",NaN,NaN
4,M 6.6 -,6.6,09-11-2022 10:14,0,2,green,1,670,us,131,4.998,27.0,mww,624.464,-25.5948,178.278,NaN,NaN,NaN

In [174]:
df['country'].value_counts().sum()

484

In [175]:
len(df.country.unique())

50

In [176]:
len(df.continent.unique())

7

In [177]:
df.describe(include='O')

,title,date_time,alert,net,magType,location,continent,country
count,782,782,415,782,782,777,206,484
unique,768,773,4,11,9,413,6,49
top,M 6.9 -,11-01-2022 11:35,green,us,mww,"Kirakira, Solomon Islands",Asia,Indonesia
freq,3,3,325,747,468,17,100,110

In [178]:
df.columns

Index(['title', 'magnitude', 'date_time', 'cdi', 'mmi', 'alert', 'tsunami',
       'sig', 'net', 'nst', 'dmin', 'gap', 'magType', 'depth', 'latitude',
       'longitude', 'location', 'continent', 'country'],
      dtype='object')

In [179]:
df.alert.value_counts()

alert
green     325
yellow     56
orange     22
red        12
Name: count, dtype: int64

In [180]:
df.isna().sum()

title          0
magnitude      0
date_time      0
cdi            0
mmi            0
alert        367
tsunami        0
sig            0
net            0
nst            0
dmin           0
gap            0
magType        0
depth          0
latitude       0
longitude      0
location       5
continent    576
country      298
dtype: int64

In [181]:
df.duplicated().sum()

0

In [182]:
df['alert'] = df['alert'].fillna('No Alert')

In [183]:
df['alert'].value_counts().sum()

782

In [184]:
df['alert']

0         green
1         green
2         green
3         green
4         green
         ...
777    No Alert
778    No Alert
779    No Alert
780    No Alert
781    No Alert
Name: alert, Length: 782, dtype: object

In [185]:
from sklearn.preprocessing import LabelEncoder

In [186]:
label = LabelEncoder()

In [187]:
df['alert'] = label.fit_transform(df['alert'])

In [188]:
df

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,1,1,768,us,117,0.509,17.0,mww,14.000,-9.7963,159.596,"Malango, Solomon Islands",Oceania,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,18-11-2022 13:37,4,4,1,0,735,us,99,2.229,34.0,mww,25.000,-4.9559,100.738,"Bengkulu, Indonesia",NaN,NaN
2,M 7.0 -,7.0,12-11-2022 07:09,3,3,1,1,755,us,147,3.125,18.0,mww,579.000,-20.0508,-178.346,NaN,Oceania,Fiji
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,11-11-2022 10:48,5,5,1,1,833,us,149,1.865,21.0,mww,37.000,-19.2918,-172.129,"Neiafu, Tonga",NaN,NaN
4,M 6.6 -,6.6,09-11-2022 10:14,0,2,1,1,670,us,131,4.998,27.0,mww,624.464,-25.5948,178.278,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,"M 7.7 - 28 km SSW of Puerto El Triunfo, El Sal...",7.7,13-01-2001 17:33,0,8,0,0,912,us,427,0.000,0.0,mwc,60.000,13.0490,-88.660,"Puerto El Triunfo, El Salvador",NaN,NaN
778,"M 6.9 - 47 km S of Old Harbor, Alaska",6.9,10-01-2001 16:02,5,7,0,0,745,ak,0,0.000,0.0,mw,36.400,56.7744,-153.281,"Old Harbor, Alaska",North America,NaN
779,"M 7.1 - 16 km NE of Port-Olry, Vanuatu",7.1,09-01-2001 16:49,0,7,0,0,776,us,372,0.000,0.0,mwb,103.000,-14.9280,167.170,"Port-Olry, Vanuatu",NaN,Vanuatu
780,"M 6.8 - Mindanao, Philippines",6.8,01-01-2001 08:54,0,5,0,0,711,us,64,0.000,0.0,mwc,33.000,6.6310,126.899,"Mindanao, Philippines",NaN,NaN
781,"M 7.5 - 21 km SE of Lukatan, Philippines",7.5,01-01-2001 06:57,0,7,0,0,865,us,324,0.000,0.0,mwc,33.000,6.8980,126.579,"Lukatan, Philippines",NaN,Philippines

In [189]:
df['title'].unique()

array(['M 7.0 - 18 km SW of Malango, Solomon Islands',
       'M 6.9 - 204 km SW of Bengkulu, Indonesia', 'M 7.0 - ',
       'M 7.3 - 205 km ESE of Neiafu, Tonga', 'M 6.6 - ',
       'M 7.0 - south of the Fiji Islands',
       'M 6.8 - south of the Fiji Islands',
       'M 6.7 - 60 km SSW of Boca Chica, Panama',
       'M 6.8 - 55 km SSW of Aguililla, Mexico',
       'M 7.6 - 35 km SSW of Aguililla, Mexico',
       'M 6.9 - 90 km E of Yujing, Taiwan',
       'M 6.5 - 96 km SE of Lugu, Taiwan',
       'M 7.0 - 209 km SSE of Isangel, Vanuatu',
       'M 7.6 - 70 km E of Kainantu, Papua New Guinea',
       'M 6.6 - 44 km SE of Kangding, China',
       'M 6.6 - south of the Kermadec Islands',
       'M 7.0 - 11 km NE of Bantay, Philippines',
       'M 6.5 - 107 km SSW of Tarauacá, Brazil',
       'M 7.2 - 10 km W of Azángaro, Peru', 'M 6.9 - ',
       'M 6.8 - 86 km NNW of San Antonio de los Cobres, Argentina',
       'M 6.6 - 55 km WSW of Masachapa, Nicaragua',
       'M 7.0 - southeast of the Loyalty Islands',
       'M 6.9 - 284 km ESE of Tadine, New Caledonia',
       'M 6.7 - 65 km S of Hualien City, Taiwan',
       'M 7.3 - 57 km ENE of Namie, Japan',
       'M 6.7 - 166 km W of Pariaman, Indonesia',
       'M 6.6 - Kermadec Islands, New Zealand',
       'M 6.5 - 49 km NW of Barranca, Peru',
       'M 6.5 - Kermadec Islands region',
       'M 6.6 - 80 km SW of Labuan, Indonesia',
       'M 6.5 - 71 km SE of Nikolski, Alaska',
       'M 6.6 - 53 km SE of Nikolski, Alaska',
       'M 6.7 - 91 km SE of Nikolski, Alaska',
       'M 6.8 - 100 km SE of Nikolski, Alaska',
       'M 6.6 - 48 km WNW of Pólis, Cyprus',
       'M 6.6 - northern Qinghai, China',
       'M 7.3 - 125 km NNE of Lospalos, Timor Leste',
       'M 7.3 - Flores Sea', 'M 7.5 - 43 km NNW of Barranca, Peru',
       'M 6.6 - 177 km SE of Hirara, Japan',
       'M 6.9 - 112 km E of Chignik, Alaska', 'M 6.9 - Vanuatu region',
       'M 7.3 - Vanuatu region',
       'M 6.5 - 80 km SW of Jiquilillo, Nicaragua',
       'M 7.0 - Acapulco, Mexico',
       'M 7.1 - South Sandwich Islands region',
       'M 6.6 - South Sandwich Islands region',
       'M 6.9 - 17 km N of Port-Olry, Vanuatu',
       'M 6.9 - South Sandwich Islands region', 'M 7.2 - Nippes, Haiti',
       'M 6.9 - 136 km SE of Perryville, Alaska',
       'M 6.9 - 125 km SE of Perryville, Alaska',
       'M 8.1 - South Sandwich Islands region',
       'M 7.5 - South Sandwich Islands region',
       'M 7.1 - 60 km ENE of Pondaguitan, Philippines',
       'M 8.2 - 91 km ESE of Perryville, Alaska',
       'M 8.2 - 99 km SE of Perryville, Alaska',
       'M 6.7 - 15 km S of Hukay, Philippines',
       'M 6.7 - 71 km S of Burica, Panama',
       'M 6.5 - Kermadec Islands, New Zealand',
       'M 6.5 - 265 km SSE of Alo, Wallis and Futuna',
       'M 7.3 - Southern Qinghai, China',
       'M 6.7 - 260 km S of Sinabang, Indonesia',
       'M 6.7 - Mauritius - Reunion region',
       'M 6.5 - 207 km WSW of Haveluloto, Tonga',
       'M 6.5 - 225 km WNW of Pangai, Tonga',
       'M 7.0 - 30 km E of Ishinomaki, Japan',
       'M 6.6 - 171 km SSE of Ust’-Kamchatsk Staryy, Russia',
       'M 8.1 - Kermadec Islands, New Zealand',
       'M 7.4 - Kermadec Islands, New Zealand',
       'M 7.3 - 182 km NE of Gisborne, New Zealand',
       'M 7.1 - 73 km ENE of Namie, Japan',
       'M 7.7 - southeast of the Loyalty Islands',
       'M 6.9 - South Shetland Islands',
       'M 7.0 - 211 km SE of Pondaguitan, Philippines',
       'M 6.7 - 29 km SSW of Turt, Mongolia',
       'M 6.7 - 146 km WNW of Corral, Chile',
       'M 7.0 - 13 km NNE of Néon Karlovásion, Greece',
       'M 7.6 - 99 km SE of Sand Point, Alaska',
       'M 6.9 - central Mid-Atlantic Ridge',
       'M 6.5 - 94 km NW of Vallenar, Chile',
       'M 6.8 - 86 km NW of Vallenar, Chile',
       'M 6.5 - central Mid-Atlantic Ridge',
       'M 6.9 - 222 km SSE of Katabu, Indonesia',
       'M 6.9 - 122 km WSW of Bengkulu, Indonesia',
       'M 6.8 - 138 km WSW of Bengkulu, Indonesia',
       'M 6.6 - 13 km E of San Pedro, Philippines',
       'M 7.8 - 99 km SSE of Perryville, Alaska',
       'M 7.0 - 114 km NNW of Popondetta, Papua New Guinea',
       'M 6.6 - 97 km N of Batang, Indonesia',
       'M 7.4 - 9 km SE of Santa María Xadani, Mexico',
       'M 7.4 - south of the Kermadec Islands',
       'M 6.6 - 130 km WNW of Naze, Japan',
       'M 6.8 - 48 km SW of San Pedro de Atacama, Chile',
       'M 6.5 - Monte Cristo Range, NV Earthquake',
       'M 6.6 - 175 km SSE of Lata, Solomon Islands', 'M 6.8 - Banda Sea',
       'M 6.5 - 91 km S of Néa Anatolí, Greece', 'M 6.5 - Stanley, Idaho',
       'M 7.5 - 221 km SSE of Severo-Kuril’sk, Russia',
       'M 7.0 - 95 km ENE of Kuril’sk, Russia',
       'M 7.7 - 123 km NNW of Lucea, Jamaica',
       'M 6.7 - 13 km N of Do?anyol, Turkey',
       'M 6.8 - 7 km S of Magsaysay, Philippines',
       'M 7.1 - 138km E of Bitung, Indonesia',
       'M 6.5 - 166km SSW of Ndoi Island, Fiji',
       'M 6.6 - 136 km W of Neiafu, Tonga',
       'M 6.5 - 2km ESE of Kisante, Philippines',
       'M 6.6 - 10 km NE of Columbio, Philippines',
       'M 6.7 - 70 km WSW of Constitución, Chile',
       'M 6.5 - 11km S of Kairatu, Indonesia',
       'M 6.6 - 34km NNE of Ndoi Island, Fiji',
       'M 6.6 - 131km S of Bristol Island, South Sandwich Islands',
       'M 6.9 - 152 km SW of Labuan, Indonesia',
       'M 6.8 - 96 km SW of San Antonio, Chile',
       'M 6.6 - 62km E of Lakatoro, Vanuatu',
       'M 7.2 - 93km NNE of Laiwui, Indonesia',
       'M 6.6 - 200km W of Broome, Australia',
       'M 6.9 - 134km WSW of Kota Ternate, Indonesia',
       'M 7.1 - 18km W of Searles Valley, CA',
       'M 7.3 - 292km NW of Saumlaki, Indonesia',
       "M 7.3 - 116km NE of L'Esperance Rock, New Zealand",
       'M 6.6 - 32 km S of La Libertad, El Salvador',
       'M 8.0 - 78 km NE of Navarro, Peru',
       'M 7.6 - 46km SSE of Namatanai, Papua New Guinea',
       'M 7.1 - 33km NW of Bulolo, Papua New Guinea',
       'M 6.8 - 98km SSW of Luwuk, Indonesia',
       'M 6.5 - 83km ENE of Bristol Island, South Sandwich Islands',
       'M 7.0 - 22 km NNE of Azángaro, Peru',
       'M 7.5 - 111km ESE of Palora, Ecuador',
       'M 6.7 - 5 km SW of Puerto Madero, Mexico',
       'M 6.7 - Prince Edward Islands region',
       'M 6.7 - 10 km SSW of Coquimbo, Chile',
       'M 6.6 - 94 km NW of Sola, Vanuatu', 'M 6.6 - Molucca Sea',
       'M 6.8 - 90km W of Tarauaca, Brazil',
       'M 7.0 - 96 km ESE of Pondaguitan, Philippines',
       'M 7.3 - 187 km SE of Ust’-Kamchatsk Staryy, Russia',
       'M 6.6 - 199 km ESE of Tadine, New Caledonia',
       'M 7.5 - 166 km ESE of Tadine, New Caledonia',
       'M 7.1 - 1 km SE of Point MacKenzie, Alaska',
       'M 6.8 - 187 km E of Levuka, Fiji',
       'M 6.7 - 120 km NW of Olonkinbyen, Svalbard and Jan Mayen',
       'M 6.8 - 32 km SW of Lithakiá, Greece',
       'M 6.5 - 237 km SW of Port McNeill, Canada',
       'M 6.8 - 210 km SW of Port McNeill, Canada',
       'M 6.5 - 223 km SW of Port McNeill, Canada',
       'M 6.5 - 171 km E of Tadine, New Caledonia',
       'M 6.7 - 269 km WNW of Ozernovskiy, Russia',
       'M 6.5 - 154 km S of Severo-Kuril’sk, Russia',
       'M 7.0 - 119 km E of Kimbe, Papua New Guinea',
       'M 6.7 - 279 km E of Levuka, Fiji',
       'M 7.5 - 72 km N of Palu, Indonesia',
       'M 6.5 - south of the Fiji Islands',
       'M 6.9 - Kermadec Islands region',
       'M 6.5 - 66 km NW of Kirakira, Solomon Islands',
       'M 7.9 - 45 km S of Levuka, Fiji',
       'M 6.6 - 27 km ESE of Chitose, Japan',
       'M 7.1 - 238 km ESE of Tadine, New Caledonia',
       'M 7.1 - 136 km W of Iñapari, Peru',
       'M 6.5 - 78 km E of Lakatoro, Vanuatu',
       'M 7.3 - 40 km ENE of Carúpano, Venezuela',
       'M 6.9 - 20 km NNW of Labuan Lombok, Indonesia',
       'M 8.2 - 267 km E of Levuka, Fiji',
       'M 6.5 - 124 km N of Labuan Bajo, Indonesia',
       'M 6.5 - 108 km WSW of Adak, Alaska',
       'M 6.9 - 36 km NW of Labuan Lombok, Indonesia',
       'M 6.9 - 18 km SSW of Leilani Estates, Hawaii',
       'M 6.8 - 38 km SE of Boyuibe, Bolivia',
       'M 6.9 - 150 km E of Kimbe, Papua New Guinea',
       'M 6.7 - 140 km E of Kimbe, Papua New Guinea',
       'M 6.8 - 103 km E of Kokopo, Papua New Guinea',
       'M 6.7 - 62 km SW of Tari, Papua New Guinea',
       'M 7.5 - 32 km SW of Tari, Papua New Guinea',
       'M 7.2 - 4 km S of Pinotepa de Don Luis, Mexico',
       'M 7.9 - 261 km SE of Chiniak, Alaska',
       'M 7.1 - 37 km W of Atiquipa, Peru',
       'M 7.5 - 203 km NNE of Barra Patuca, Honduras',
       'M 6.5 - 12 km SSW of Kawalu, Indonesia',
       'M 6.5 - Bouvet Island region',
       'M 7.0 - 85 km ENE of Tadine, New Caledonia',
       'M 6.6 - 74 km E of Tadine, New Caledonia',
       'M 6.5 - 18 km W of Parrita, Costa Rica',
       'M 7.3 - 29 km S of ?alabja, Iraq',
       'M 6.5 - 67 km WSW of Angoram, Papua New Guinea',
       'M 6.8 - 97 km NE of Hihifo, Tonga',
       'M 6.6 - 101 km E of Tadine, New Caledonia',
       'M 6.7 - 132 km E of Tadine, New Caledonia',
       'M 6.7 - 181 km NNE of Maumere, Indonesia',
       'M 6.5 - 247 km ESE of Attu Station, Alaska',
       'M 7.1 - 1 km S of Matzaco, Mexico',
       'M 8.2 - near the coast of Chiapas, Mexico',
       'M 6.5 - 168 km SW of Mawu, China',
       'M 6.6 - 11 km ENE of Kos, Greece',
       'M 7.7 - Komandorskiye Ostrova, Russia region',
       'M 6.6 - Auckland Islands, New Zealand region',
       'M 6.5 - 2 km S of Lim-oo, Philippines',
       'M 6.8 - 28 km SW of Puerto San José, Guatemala',
       'M 6.9 - 2 km SSW of San Pablo, Guatemala',
       'M 6.8 - 200 km NW of Attu Station, Alaska',
       'M 6.6 - 37 km WNW of Poso, Indonesia',
       'M 6.5 - South Sandwich Islands region',
       'M 6.8 - 59 km NNE of Port-Olry, Vanuatu',
       'M 6.9 - 31 km SW of Burias, Philippines',
       'M 6.9 - 40 km W of Valparaíso, Chile',
       'M 6.5 - 132 km WSW of Moijabana, Botswana',
       'M 6.6 - 81 km NNE of Ust’-Kamchatsk Staryy, Russia',
       'M 6.9 - south of the Fiji Islands',
       'M 6.5 - 41 km E of Padilla, Bolivia',
       'M 6.5 - 11 km N of Mabua, Philippines',
       'M 7.9 - 35 km WNW of Panguna, Papua New Guinea',
       'M 6.5 - 65 km W of Kirakira, Solomon Islands',
       'M 7.3 - 189 km SSE of Tabiauan, Philippines',
       'M 6.9 - 225 km SW of Nadi, Fiji',
       'M 7.6 - 41 km SW of Quellón, Chile',
       'M 6.7 - 151 km NE of Lospalos, Timor Leste',
       'M 7.9 - 140 km E of Kokopo, Papua New Guinea',
       'M 6.9 - 92 km WSW of Kirakira, Solomon Islands',
       'M 6.5 - 79 km WSW of Kirakira, Solomon Islands',
       'M 7.8 - 69 km WSW of Kirakira, Solomon Islands',
       'M 6.6 - 164 km W of Ferndale, California',
       'M 6.5 - 14 km WNW of Reuleuet, Indonesia',
       'M 6.6 - 122 km N of Murghob, Tajikistan',
       'M 6.9 - 156 km SSW of Puerto El Triunfo, El Salvador',
       'M 6.9 - 35 km ESE of Namie, Japan',
       'M 6.5 - 74 km NE of Amberley, New Zealand',
       'M 6.5 - 92 km SSW of Blenheim, New Zealand',
       'M 7.8 - 53 km NNE of Amberley, New Zealand',
       'M 6.6 - 5 km ESE of Preci, Italy',
       'M 6.6 - 161 km NNE of Pamanukan, Indonesia',
       'M 6.8 - 76 km WNW of Kandrian, Papua New Guinea',
       'M 6.9 - Fiji region',
       'M 7.0 - 175 km NE of Gisborne, New Zealand',
       'M 6.8 - 90 km NE of Rabaul, Papua New Guinea',
       'M 6.8 - 26 km W of Chauk, Myanmar',
       'M 7.2 - southeast of the Loyalty Islands',
       'M 7.7 - Pagan region, Northern Mariana Islands',
       'M 6.6 - 80 km W of Sungai Penuh, Indonesia',
       'M 7.2 - South Sandwich Islands region',
       'M 6.9 - 24 km NW of Rosa Zarate, Ecuador',
       'M 6.7 - 32 km SE of Muisne, Ecuador',
       'M 7.0 - 3 km NW of Norsup, Vanuatu',
       'M 7.8 - 27 km SSE of Muisne, Ecuador',
       'M 7.0 - 6 km ESE of Kumamoto, Japan',
       'M 6.9 - 76 km SE of Mawlaik, Myanmar',
       'M 6.6 - 42 km WSW of Ashk?sham, Afghanistan',
       'M 6.7 - 104 km W of Sola, Vanuatu',
       'M 6.7 - 102 km WSW of Sola, Vanuatu',
       'M 6.9 - 82 km NNW of Port-Olry, Vanuatu',
       'M 7.8 - southwest of Sumatra, Indonesia',
       'M 7.2 - 80 km S of Mil’kovo, Russia',
       'M 7.1 - 47 km ESE of Pedro Bay, Alaska',
       'M 6.6 - 203 km SW of La Cruz de Loreto, Mexico',
       'M 6.7 - 52 km SE of Shizunai-furukawach?, Japan',
       'M 6.5 - 227 km SE of Sarangani, Philippines',
       'M 6.7 - 29 km W of Imph?l, India',
       'M 6.6 - 4 km W of Manuel Ávila Camacho (Ponte Duro), Mexico',
       'M 6.9 - 107 km SE of Amahai, Indonesia',
       'M 7.2 - 104 km W of Murghob, Tajikistan',
       'M 6.7 - 125 km SSW of Tarauacá, Brazil',
       'M 7.6 - 185 km WNW of Iñapari, Peru',
       'M 7.6 - 155 km WNW of Iñapari, Peru',
       'M 6.8 - 153 km WSW of Buala, Solomon Islands',
       'M 6.5 - 19 km SSW of Lefkáda, Greece',
       'M 6.7 - 140 km WSW of Makurazaki, Japan',
       'M 6.9 - 85 km NW of Coquimbo, Chile',
       'M 6.9 - 81 km NW of Coquimbo, Chile',
       'M 6.6 - Nicobar Islands, India region',
       'M 6.8 - 39 km SW of Ovalle, Chile',
       'M 6.5 - 47 km NW of Maubara, Timor Leste',
       'M 7.5 - Hindu Kush region, Afghanistan',
       'M 7.1 - 31 km NE of Port-Olry, Vanuatu',
       'M 6.6 - 28 km N of Sorong, Indonesia',
       'M 6.6 - 22 km WSW of Illapel, Chile',
       'M 6.7 - 61 km WNW of Illapel, Chile',
       'M 6.5 - 54 km WNW of Illapel, Chile',
       'M 7.0 - 25 km WNW of Illapel, Chile',
       'M 8.3 - 48 km W of Illapel, Chile',
       'M 6.7 - 95 km SW of Topolobampo, Mexico',
       'M 6.5 - 177 km SE of Gizo, Solomon Islands',
       'M 6.6 - 186 km WNW of Malango, Solomon Islands',
       'M 7.0 - 234 km W of Abepura, Indonesia',
       'M 6.9 - Fox Islands, Aleutian Islands, Alaska',
       'M 7.0 - 80 km WNW of Lata, Solomon Islands',
       'M 6.5 - 128 km NE of Bathsheba, Barbados',
       'M 6.7 - 150 km WNW of Malango, Solomon Islands',
       'M 6.5 - Bonin Islands, Japan region',
       'M 7.8 - Bonin Islands, Japan region',
       'M 6.8 - 117 km SSE of Ugashik, Alaska',
       'M 6.8 - 159 km ESE of Kirakira, Solomon Islands',
       'M 6.9 - 205 km ESE of Kirakira, Solomon Islands',
       'M 6.8 - 178 km W of Lata, Solomon Islands',
       'M 6.8 - 32 km SE of ?funato, Japan', 'M 7.3 - Nepal',
       'M 7.1 - 143 km SW of Panguna, Papua New Guinea',
       'M 7.5 - 131 km SSW of Kokopo, Papua New Guinea',
       'M 6.8 - 109 km SSW of Kokopo, Papua New Guinea',
       'M 6.7 - 126 km SSW of Kokopo, Papua New Guinea',
       'M 6.7 - 21 km SSE of Kod?ri??, Nepal',
       'M 6.6 - 71 km NNE of Bharatpur, Nepal',
       'M 7.8 - 67 km NNE of Bharatpur, Nepal',
       'M 6.5 - 181 km SSW of Alo, Wallis and Futuna',
       'M 6.5 - 96 km ENE of Hihifo, Tonga',
       'M 7.5 - 53 km SE of Kokopo, Papua New Guinea',
       'M 7.0 - 150 km NNE of Maumere, Indonesia',
       'M 6.7 - 83 km ENE of Miyako, Japan',
       'M 6.7 - 103 km W of El Aguilar, Argentina',
       'M 6.8 - 81 km NNE of Port-Vila, Vanuatu',
       'M 6.5 - 236 km S of Punta de Burica, Panama',
       'M 6.6 - 22 km ESE of Punta de Burica, Panama',
       'M 6.6 - 115 km W of Panguna, Papua New Guinea',
       'M 6.6 - 106 km WSW of Sangay, Philippines',
       'M 6.8 - 157 km NW of Ternate, Indonesia',
       'M 6.5 - 123 km WNW of Tobelo, Indonesia',
       'M 6.7 - 183 km NE of Gisborne, New Zealand',
       'M 7.1 - 155 km NW of Ternate, Indonesia',
       'M 6.6 - 76 km NE of Finschhafen, Papua New Guinea',
       'M 7.1 - Fiji region', 'M 7.3 - 74 km S of Intipucá, El Salvador',
       'M 6.7 - 43 km NW of Piti Village, Guam',
       'M 6.8 - 38 km NW of Aniso, Peru',
       'M 6.9 - Federated States of Micronesia region',
       'M 6.5 - 139 km ESE of Namie, Japan',
       'M 6.9 - 4 km W of Puerto Madero, Mexico',
       'M 6.5 - 217 km SSE of Kokopo, Papua New Guinea',
       'M 6.7 - 201 km SSE of Mata-Utu, Wallis and Futuna',
       'M 7.9 - Rat Islands, Aleutian Islands, Alaska',
       'M 6.7 - Kermadec Islands, New Zealand',
       'M 6.9 - Kermadec Islands, New Zealand',
       'M 6.9 - 21 km SSW of Kamariótissa, Greece',
       'M 6.5 - 110 km SE of Punta de Burica, Panama',
       'M 6.6 - 239 km SSE of Isangel, Vanuatu',
       'M 6.5 - 107 km WSW of Vernon, Canada',
       'M 7.5 - 70 km SW of Panguna, Papua New Guinea',
       'M 6.6 - 57 km SW of Panguna, Papua New Guinea',
       'M 7.2 - 9 km ENE of Coyuquilla Norte, Mexico',
       'M 6.6 - 75 km S of Kirakira, Solomon Islands',
       'M 7.4 - 112 km S of Kirakira, Solomon Islands',
       'M 7.6 - 93 km SSE of Kirakira, Solomon Islands',
       'M 6.6 - 15 km N of Belén, Nicaragua',
       'M 6.5 - 78 km SW of Panguna, Papua New Guinea',
       'M 7.1 - 56 km WSW of Panguna, Papua New Guinea',
       'M 7.7 - 53 km SW of Iquique, Chile',
       'M 6.5 - 45 km WSW of Iquique, Chile',
       'M 6.9 - 90 km WNW of Iquique, Chile',
       'M 8.2 - 93 km NW of Iquique, Chile',
       'M 6.7 - 63 km WNW of Iquique, Chile',
       'M 6.8 - 77 km WNW of Indianola, California',
       'M 6.5 - 109 km NW of Nago, Japan',
       'M 6.5 - 171 km NNE of Greenland, Barbados',
       'M 6.9 - 272 km ESE of Hotan, China',
       'M 6.5 - 32 km E of Port-Olry, Vanuatu',
       'M 6.5 - south of the Kermadec Islands',
       'M 6.5 - 32 km W of Sola, Vanuatu', 'M 6.5 - Fiji region',
       'M 7.7 - Scotia Sea', 'M 6.9 - Scotia Sea',
       'M 6.6 - 41 km SSW of Coquimbo, Chile',
       'M 7.1 - off the east coast of Honshu, Japan',
       'M 6.6 - 98 km SW of Etchoropo, Mexico',
       'M 6.8 - 62 km WSW of Panguna, Papua New Guinea',
       'M 7.1 - 4 km SE of Sagbayan, Philippines',
       'M 6.6 - 36 km W of Kíssamos, Greece', 'M 6.7 - Sea of Okhotsk',
       'M 6.8 - 129 km WSW of Khuzdar, Pakistan',
       'M 7.1 - 16 km WSW of Atiquipa, Peru',
       'M 7.7 - 113 km NW of Bela, Pakistan',
       'M 6.5 - 81 km SSW of Atka, Alaska',
       'M 6.5 - Izu Islands, Japan region',
       'M 6.5 - 180 km NE of Lospalos, Timor Leste',
       'M 7.0 - 101 km SW of Atka, Alaska',
       'M 6.5 - 29 km SE of Blenheim, New Zealand',
       'M 6.7 - 101 km WSW of Bahía Solano, Colombia',
       'M 6.5 - 38 km ESE of Blenheim, New Zealand',
       'M 7.3 - South Sandwich Islands region',
       'M 6.6 - 26 km NE of Kandrian, Papua New Guinea',
       'M 7.3 - 190 km ENE of Kokopo, Papua New Guinea',
       'M 6.6 - northern Mid-Atlantic Ridge',
       'M 6.5 - 44 km W of Masachapa, Nicaragua',
       'M 6.7 - south of Java, Indonesia', 'M 8.3 - Sea of Okhotsk',
       'M 7.4 - 292 km SW of Vaini, Tonga',
       'M 6.8 - Pagan region, Northern Mariana Islands',
       'M 6.5 - 33 km N of Rabaul, Papua New Guinea',
       'M 6.6 - 56 km WSW of Linqiong, China',
       'M 7.2 - 252 km ENE of Kuril’sk, Russia',
       'M 6.6 - 23 km ESE of Aitape, Papua New Guinea',
       'M 7.7 - 79 km ESE of Kh?sh, Iran',
       'M 6.6 - 98 km W of Panguna, Papua New Guinea',
       'M 7.0 - 260 km WSW of Abepura, Indonesia',
       'M 6.5 - 36 km E of Finschhafen, Papua New Guinea',
       'M 6.5 - 87 km SE of Ozernovskiy, Russia',
       'M 6.9 - 81 km SE of Ozernovskiy, Russia',
       'M 6.6 - 183 km SW of Belaya Gora, Russia',
       'M 6.6 - 30 km SSW of Lata, Solomon Islands',
       'M 6.9 - 2 km NNE of Yacuanquer, Colombia',
       'M 7.1 - 32 km SE of Lata, Solomon Islands',
       'M 6.8 - 22 km ESE of Lata, Solomon Islands',
       'M 6.7 - 33 km SSW of Lata, Solomon Islands',
       'M 7.0 - 33 km NW of Lata, Solomon Islands',
       'M 7.1 - 112 km WSW of Lata, Solomon Islands',
       'M 8.0 - 75 km W of Lata, Solomon Islands',
       'M 6.9 - 18 km SSW of Obihiro, Japan',
       'M 6.8 - 54 km N of Vallenar, Chile',
       'M 7.5 - 110 km SW of Edna Bay, Alaska',
       'M 6.7 - 59 km SSW of Sola, Vanuatu', 'M 7.1 - Banda Sea',
       'M 7.3 - 234 km SE of ?funato, Japan',

In [190]:
pip install reverse_geocoder

Requirement already satisfied: reverse_geocoder in e:\anaconda hehehe\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.11.0 in e:\anaconda hehehe\lib\site-packages (from reverse_geocoder) (1.26.4)
Requirement already satisfied: scipy>=0.17.1 in e:\anaconda hehehe\lib\site-packages (from reverse_geocoder) (1.13.1)
Note: you may need to restart the kernel to use updated packages.

In [191]:
import reverse_geocoder as rg

def get_country_rg(lat, lon):
    try:
        result = rg.search((lat, lon))  # tuple
        return result[0]['cc']  # country code
    except:
        return None

In [192]:
coords = list(zip(df['latitude'], df['longitude']))

results = rg.search(coords)

In [193]:
results

[{'lat': '-9.43333',
  'lon': '159.95',
  'name': 'Honiara',
  'admin1': 'Guadalcanal',
  'admin2': '',
  'cc': 'SB'},
 {'lat': '-3.3897',
  'lon': '101.8352',
  'name': 'Ketahun',
  'admin1': 'Bengkulu',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-21.15216',
  'lon': '-175.21333',
  'name': 'Haveluloto',
  'admin1': 'Tongatapu',
  'admin2': '',
  'cc': 'TO'},
 {'lat': '-18.65',
  'lon': '-173.98333',
  'name': 'Neiafu',
  'admin1': 'Vava`u',
  'admin2': '',
  'cc': 'TO'},
 {'lat': '-18.14161',
  'lon': '178.44149',
  'name': 'Suva',
  'admin1': 'Central',
  'admin2': '',
  'cc': 'FJ'},
 {'lat': '-18.14161',
  'lon': '178.44149',
  'name': 'Suva',
  'admin1': 'Central',
  'admin2': '',
  'cc': 'FJ'},
 {'lat': '-18.14161',
  'lon': '178.44149',
  'name': 'Suva',
  'admin1': 'Central',
  'admin2': '',
  'cc': 'FJ'},
 {'lat': '8.03333',
  'lon': '-82.86667',
  'name': 'Punta de Burica',
  'admin1': 'Chiriqui',
  'admin2': '',
  'cc': 'PA'},
 {'lat': '18.73843',
  'lon': '-102.79032',
  'name': 'Aguililla',
  'admin1': 'Michoacan',
  'admin2': '',
  'cc': 'MX'},
 {'lat': '18.7775',
  'lon': '-103.16',
  'name': 'Coalcoman de Vazquez Pallares',
  'admin1': 'Michoacan',
  'admin2': 'Coalcoman de Vazquez Pallares',
  'cc': 'MX'},
 {'lat': '22.75991',
  'lon': '121.14457',
  'name': 'Taitung',
  'admin1': 'Taiwan',
  'admin2': 'Taitung',
  'cc': 'TW'},
 {'lat': '22.75991',
  'lon': '121.14457',
  'name': 'Taitung',
  'admin1': 'Taiwan',
  'admin2': 'Taitung',
  'cc': 'TW'},
 {'lat': '-19.55',
  'lon': '169.26667',
  'name': 'Isangel',
  'admin1': 'Tafea',
  'admin2': '',
  'cc': 'VU'},
 {'lat': '-6.28872',
  'lon': '145.86548',
  'name': 'Kainantu',
  'admin1': 'Eastern Highlands',
  'admin2': '',
  'cc': 'PG'},
 {'lat': '29.93246',
  'lon': '102.23163',
  'name': 'Luqiao',
  'admin1': 'Sichuan',
  'admin2': '',
  'cc': 'CN'},
 {'lat': '-43.95353',
  'lon': '-176.55973',
  'name': 'Waitangi',
  'admin1': 'Chatham Islands',
  'admin2': '',
  'cc': 'NZ'},
 {'lat': '17.6125',
  'lon': '120.7358',
  'name': 'Lagangilang',
  'admin1': 'Cordillera',
  'admin2': 'Province of Abra',
  'cc': 'PH'},
 {'lat': '-8.16139',
  'lon': '-70.76556',
  'name': 'Tarauaca',
  'admin1': 'Acre',
  'admin2': 'Tarauaca',
  'cc': 'BR'},
 {'lat': '-14.78333',
  'lon': '-70.35',
  'name': 'Asillo',
  'admin1': 'Puno',
  'admin2': 'Provincia de Azangaro',
  'cc': 'PE'},
 {'lat': '-46.35',
  'lon': '168.01667',
  'name': 'Riverton',
  'admin1': 'Southland',
  'admin2': 'Southland District',
  'cc': 'NZ'},
 {'lat': '-23.39864',
  'lon': '-66.36701',
  'name': 'Susques',
  'admin1': 'Jujuy',
  'admin2': 'Departamento de Susques',
  'cc': 'AR'},
 {'lat': '11.78687',
  'lon': '-86.51416',
  'name': 'Masachapa',
  'admin1': 'Managua',
  'admin2': '',
  'cc': 'NI'},
 {'lat': '-21.55',
  'lon': '167.88333',
  'name': 'Tadine',
  'admin1': 'Loyalty Islands',
  'admin2': 'Mare',
  'cc': 'NC'},
 {'lat': '-21.55',
  'lon': '167.88333',
  'name': 'Tadine',
  'admin1': 'Loyalty Islands',
  'admin2': 'Mare',
  'cc': 'NC'},
 {'lat': '23.97694',
  'lon': '121.60444',
  'name': 'Hualian',
  'admin1': 'Taiwan',
  'admin2': 'Hualien',
  'cc': 'TW'},
 {'lat': '37.48333',
  'lon': '141',
  'name': 'Namie',
  'admin1': 'Fukushima',
  'admin2': '',
  'cc': 'JP'},
 {'lat': '-1.11961',
  'lon': '98.99217',
  'name': 'Sikabaluan',
  'admin1': 'West Sumatra',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-21.33333',
  'lon': '-174.95',
  'name': '`Ohonua',
  'admin1': "'Eua",
  'admin2': '',
  'cc': 'TO'},
 {'lat': '-21.15216',
  'lon': '-175.21333',
  'name': 'Haveluloto',
  'admin1': 'Tongatapu',
  'admin2': '',
  'cc': 'TO'},
 {'lat': '-4.83298',
  'lon': '-76.67582',
  'name': 'Barranca',
  'admin1': 'Loreto',
  'admin2': 'Datem Del Maranon',
  'cc': 'PE'},
 {'lat': '-21.33333',
  'lon': '-174.95',
  'name': '`Ohonua',
  'admin1': "'Eua",
  'admin2': '',
  'cc': 'TO'},
 {'lat': '-6.8092',
  'lon': '105.6292',
  'name': 'Tugu Hilir',
  'admin1': 'Banten',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '53.87361',
  'lon': '-166.53667',
  'name': 'Unalaska',
  'admin1': 'Alaska',
  'admin2': 'Aleutians West Census Area',
  'cc': 'US'},
 {'lat': '53.87361',
  'lon': '-166.53667',
  'name': 'Unalaska',
  'admin1': 'Alaska',
  'admin2': 'Aleutians West Census Area',
  'cc': 'US'},
 {'lat': '53.87361',
  'lon': '-166.53667',
  'name': 'Unalaska',
  'admin1': 'Alaska',
  'admin2': 'Aleutians West Census Area',
  'cc': 'US'},
 {'lat': '53.87361',
  'lon': '-166.53667',
  'name': 'Unalaska',
  'admin1': 'Alaska',
  'admin2': 'Aleutians West Census Area',
  'cc': 'US'},
 {'lat': '53.87361',
  'lon': '-166.53667',
  'name': 'Unalaska',
  'admin1': 'Alaska',
  'admin2': 'Aleutians West Census Area',
  'cc': 'US'},
 {'lat': '53.87361',
  'lon': '-166.53667',
  'name': 'Unalaska',
  'admin1': 'Alaska',
  'admin2': 'Aleutians West Census Area',
  'cc': 'US'},
 {'lat': '35.03534',
  'lon': '32.42575',
  'name': 'Polis',
  'admin1': 'Pafos',
  'admin2': '',
  'cc': 'CY'},
 {'lat': '37.60942',
  'lon': '101.20058',
  'name': 'Huangcheng',
  'admin1': 'Qinghai Sheng',
  'admin2': '',
  'cc': 'CN'},
 {'lat': '-8.51861',
  'lon': '127.0025',
  'name': 'Lospalos',
  'admin1': 'Lautem',
  'admin2': '',
  'cc': 'TL'},
 {'lat': '-8.35014',
  'lon': '122.32091',
  'name': 'Pemana',
  'admin1': 'East Nusa Tenggara',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-4.83298',
  'lon': '-76.67582',
  'name': 'Barranca',
  'admin1': 'Loreto',
  'admin2': 'Datem Del Maranon',
  'cc': 'PE'},
 {'lat': '24.80379',
  'lon': '125.30222',
  'name': 'Hirara',
  'admin1': 'Okinawa',
  'admin2': '',
  'cc': 'JP'},
 {'lat': '59.03972',
  'lon': '-158.4575',
  'name': 'Dillingham',
  'admin1': 'Alaska',
  'admin2': 'Dillingham Census Area',
  'cc': 'US'},
 {'lat': '-17.8',
  'lon': '177.41667',
  'name': 'Nadi',
  'admin1': 'Western',
  'admin2': '',
  'cc': 'FJ'},
 {'lat': '-17.8',
  'lon': '177.41667',
  'name': 'Nadi',
  'admin1': 'Western',
  'admin2': '',
  'cc': 'FJ'},
 {'lat': '12.74593',
  'lon': '-87.4516',
  'name': 'Jiquilillo',
  'admin1': 'Chinandega',
  'admin2': '',
  'cc': 'NI'},
 {'lat': '16.99778',
  'lon': '-99.78',
  'name': 'Kilometro 30',
  'admin1': 'Guerrero',
  'admin2': 'Acapulco de Juarez',
  'cc': 'MX'},
 {'lat': '-54.28111',
  'lon': '-36.5092',
  'name': 'Grytviken',
  'admin1': '',
  'admin2': '',
  'cc': 'GS'},
 {'lat': '-54.28111',
  'lon': '-36.5092',
  'name': 'Grytviken',
  'admin1': '',
  'admin2': '',
  'cc': 'GS'},
 {'lat': '-15.04175',
  'lon': '167.07265',
  'name': 'Port-Olry',
  'admin1': 'Sanma',
  'admin2': '',
  'cc': 'VU'},
 {'lat': '-54.28111',
  'lon': '-36.5092',
  'name': 'Grytviken',
  'admin1': '',
  'admin2': '',
  'cc': 'GS'},
 {'lat': '18.28333',
  'lon': '-73.4',
  'name': 'Aquin',
  'admin1': 'Sud',
  'admin2': '',
  'cc': 'HT'},
 {'lat': '55.33655',
  'lon': '-160.4988',
  'name': 'Sand Point',
  'admin1': 'Alaska',
  'admin2': 'Aleutians East Borough',
  'cc': 'US'},
 {'lat': '55.33655',
  'lon': '-160.4988',
  'name': 'Sand Point',
  'admin1': 'Alaska',
  'admin2': 'Aleutians East Borough',
  'cc': 'US'},
 {'lat': '-54.28111',
  'lon': '-36.5092',
  'name': 'Grytviken',
  'admin1': '',
  'admin2': '',
  'cc': 'GS'},
 {'lat': '-54.28111',
  'lon': '-36.5092',
  'name': 'Grytviken',
  'admin1': '',
  'admin2': '',
  'cc': 'GS'},
 {'lat': '6.36115',
  'lon': '126.17778',
  'name': 'Pondaguitan',
  'admin1': 'Davao',
  'admin2': 'Province of Davao Oriental',
  'cc': 'PH'},
 {'lat': '55.33655',
  'lon': '-160.4988',
  'name': 'Sand Point',
  'admin1': 'Alaska',
  'admin2': 'Aleutians East Borough',
  'cc': 'US'},
 {'lat': '55.33655',
  'lon': '-160.4988',
  'name': 'Sand Point',
  'admin1': 'Alaska',
  'admin2': 'Aleutians East Borough',
  'cc': 'US'},
 {'lat': '13.84519',
  'lon': '120.70287',
  'name': 'Hukay',
  'admin1': 'Calabarzon',
  'admin2': 'Province of Batangas',
  'cc': 'PH'},
 {'lat': '8.03333',
  'lon': '-82.86667',
  'name': 'Punta de Burica',
  'admin1': 'Chiriqui',
  'admin2': '',
  'cc': 'PA'},
 {'lat': '-21.33333',
  'lon': '-174.95',
  'name': '`Ohonua',
  'admin1': "'Eua",
  'admin2': '',
  'cc': 'TO'},
 {'lat': '-14.31096',
  'lon': '-178.11094',
  'name': 'Alo',
  'admin1': "Circonscription d'Alo",
  'admin2': '',
  'cc': 'WF'},
 {'lat': '34.56667',
  'lon': '98.31667',
  'name': 'Huanghe',
  'admin1': 'Qinghai Sheng',
  'admin2': '',
  'cc': 'CN'},
 {'lat': '2.22532',
  'lon': '97.23413',
  'name': 'Pulo Batal',
  'admin1': 'Aceh',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-19.68333',
  'lon': '63.41667',
  'name': 'Port Mathurin',
  'admin1': 'Rodrigues',
  'admin2': '',
  'cc': 'MU'},
 {'lat': '38.44491',
  'lon': '141.43269',
  'name': 'Onagawa Cho',
  'admin1': 'Miyagi',
  'admin2': 'Oshika Gun',
  'cc': 'JP'},
 {'lat': '-21.15216',
  'lon': '-175.21333',
  'name': 'Haveluloto',
  'admin1': 'Tongatapu',
  'admin2': '',
  'cc': 'TO'},
 {'lat': '-19.81468',
  'lon': '-174.35423',
  'name': 'Pangai',
  'admin1': 'Ha`apai',
  'admin2': '',
  'cc': 'TO'},
 {'lat': '38.44491',
  'lon': '141.43269',
  'name': 'Onagawa Cho',
  'admin1': 'Miyagi',
  'admin2': 'Oshika Gun',
  'cc': 'JP'},
 {'lat': '56.22778',
  'lon': '162.47778',
  'name': "Ust'-Kamchatsk Staryy",
  'admin1': 'Kamtsjatka',
  'admin2': '',
  'cc': 'RU'},
 {'lat': '-21.33333',
  'lon': '-174.95',
  'name': '`Ohonua',
  'admin1': "'Eua",
  'admin2': '',
  'cc': 'TO'},
 {'lat': '-21.33333',
  'lon': '-174.95',
  'name': '`Ohonua',
  'admin1': "'Eua",
  'admin2': '',
  'cc': 'TO'},
 {'lat': '-21.33333',
  'lon': '-174.95',
  'name': '`Ohonua',
  'admin1': "'Eua",
  'admin2': '',
  'cc': 'TO'},
 {'lat': '-38.65333',
  'lon': '178.00417',
  'name': 'Gisborne',
  'admin1': 'Gisborne',
  'admin2': 'Gisborne District',
  'cc': 'NZ'},
 {'lat': '38.44491',
  'lon': '141.43269',
  'name': 'Onagawa Cho',
  'admin1': 'Miyagi',
  'admin2': 'Oshika Gun',
  'cc': 'JP'},
 {'lat': '-21.55',
  'lon': '167.88333',
  'name': 'Tadine',
  'admin1': 'Loyalty Islands',
  'admin2': 'Mare',
  'cc': 'NC'},
 {'lat': '-51.7',
  'lon': '-57.85',
  'name': 'Stanley',
  'admin1': '',
  'admin2': '',
  'cc': 'FK'},
 {'lat': '4.45501',
  'lon': '126.73859',
  'name': 'Essang',
  'admin1': 'North Sulawesi',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '51.50725',
  'lon': '100.66257',
  'name': 'Turt',
  'admin1': 'Hovsgol',
  'admin2': '',
  'cc': 'MN'},
 {'lat': '-39.8873',
  'lon': '-73.43101',
  'name': 'Corral',
  'admin1': 'Los Lagos',
  'admin2': '',
  'cc': 'CL'},
 {'lat': '37.79209',
  'lon': '26.7049',
  'name': 'Neon Karlovasion',
  'admin1': 'North Aegean',
  'admin2': 'Nomos Samou',
  'cc': 'GR'},
 {'lat': '55.33655',
  'lon': '-160.4988',
  'name': 'Sand Point',
  'admin1': 'Alaska',
  'admin2': 'Aleutians East Borough',
  'cc': 'US'},
 {'lat': '-3.84028',
  'lon': '-32.41083',
  'name': 'Fernando de Noronha (Distrito Estadual)',
  'admin1': 'Pernambuco',
  'admin2': 'Fernando De Noronha',
  'cc': 'BR'},
 {'lat': '-28.57617',
  'lon': '-70.75938',
  'name': 'Vallenar',
  'admin1': 'Atacama',
  'admin2': 'Provincia de Huasco',
  'cc': 'CL'},
 {'lat': '-28.57617',
  'lon': '-70.75938',
  'name': 'Vallenar',
  'admin1': 'Atacama',
  'admin2': 'Provincia de Huasco',
  'cc': 'CL'},
 {'lat': '-3.84028',
  'lon': '-32.41083',
  'name': 'Fernando de Noronha (Distrito Estadual)',
  'admin1': 'Pernambuco',
  'admin2': 'Fernando De Noronha',
  'cc': 'BR'},
 {'lat': '-8.1731',
  'lon': '123.7744',
  'name': 'Bareng',
  'admin1': 'East Nusa Tenggara',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-3.3897',
  'lon': '101.8352',
  'name': 'Ketahun',
  'admin1': 'Bengkulu',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-3.3897',
  'lon': '101.8352',
  'name': 'Ketahun',
  'admin1': 'Bengkulu',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '12.05',
  'lon': '124.15',
  'name': 'Tagapul-an',
  'admin1': 'Eastern Visayas',
  'admin2': 'Province of Samar',
  'cc': 'PH'},
 {'lat': '55.33655',
  'lon': '-160.4988',
  'name': 'Sand Point',
  'admin1': 'Alaska',
  'admin2': 'Aleutians East Borough',
  'cc': 'US'},
 {'lat': '-8.87778',
  'lon': '147.73642',
  'name': 'Kokoda',
  'admin1': 'Northern Province',
  'admin2': 'Sohe',
  'cc': 'PG'},
 {'lat': '-6.4846',
  'lon': '110.7083',
  'name': 'Batang',
  'admin1': 'Central Java',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '15.94825',
  'lon': '-96.07364',
  'name': 'Santa Maria Xadani',
  'admin1': 'Oaxaca',
  'admin2': '',
  'cc': 'MX'},
 {'lat': '-43.95353',
  'lon': '-176.55973',
  'name': 'Waitangi',
  'admin1': 'Chatham Islands',
  'admin2': '',
  'cc': 'NZ'},
 {'lat': '28.36667',
  'lon': '129.48333',
  'name': 'Naze',
  'admin1': 'Kagoshima',
  'admin2': '',
  'cc': 'JP'},
 {'lat': '-22.9111',
  'lon': '-68.20113',
  'name': 'San Pedro de Atacama',
  'admin1': 'Antofagasta',
  'admin2': 'Provincia de El Loa',
  'cc': 'CL'},
 {'lat': '38.06716',
  'lon': '-117.23008',
  'name': 'Tonopah',
  'admin1': 'Nevada',
  'admin2': 'Nye County',
  'cc': 'US'},
 {'lat': '-10.71667',
  'lon': '165.83333',
  'name': 'Lata',
  'admin1': 'Temotu',
  'admin2': '',
  'cc': 'SB'},
 {'lat': '-3.8732',
  'lon': '130.9254',
  'name': 'Geser',
  'admin1': 'Maluku',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '35.01186',
  'lon': '25.74234',
  'name': 'Ierapetra',
  'admin1': 'Crete',
  'admin2': 'Nomos Lasithiou',
  'cc': 'GR'},
 {'lat': '44.50464',
  'lon': '-114.23173',
  'name': 'Challis',
  'admin1': 'Idaho',
  'admin2': 'Custer County',
  'cc': 'US'},
 {'lat': '50.67531',
  'lon': '156.12695',
  'name': "Severo-Kuril'sk",
  'admin1': 'Sakhalin',
  'admin2': '',
  'cc': 'RU'},
 {'lat': '45.22686',
  'lon': '147.87767',
  'name': "Kuril'sk",
  'admin1': 'Hokkaido',
  'admin2': '',
  'cc': 'JP'},
 {'lat': '18.45095',
  'lon': '-78.17356',
  'name': 'Lucea',
  'admin1': 'Hanover',
  'admin2': '',
  'cc': 'JM'},
 {'lat': '38.4313',
  'lon': '39.06387',
  'name': 'Gozeli',
  'admin1': 'Elazig',
  'admin2': '',
  'cc': 'TR'},
 {'lat': '6.76667',
  'lon': '125.18333',
  'name': 'Magsaysay',
  'admin1': 'Davao',
  'admin2': 'Province of Davao del Sur',
  'cc': 'PH'},
 {'lat': '1.15125',
  'lon': '127.43243',
  'name': 'Susupu',
  'admin1': 'Maluku Utara',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-21.15216',
  'lon': '-175.21333',
  'name': 'Haveluloto',
  'admin1': 'Tongatapu',
  'admin2': '',
  'cc': 'TO'},
 {'lat': '-18.65',
  'lon': '-173.98333',
  'name': 'Neiafu',
  'admin1': 'Vava`u',
  'admin2': '',
  'cc': 'TO'},
 {'lat': '6.9025',
  'lon': '125.16083',
  'name': 'Bulatukan',
  'admin1': 'Soccsksargen',
  'admin2': 'Province of North Cotabato',
  'cc': 'PH'},
 {'lat': '6.69639',
  'lon': '124.93722',
  'name': 'Columbio',
  'admin1': 'Soccsksargen',
  'admin2': 'Province of Sultan Kudarat',
  'cc': 'PH'},
 {'lat': '-35.33321',
  'lon': '-72.41156',
  'name': 'Constitucion',
  'admin1': 'Maule',
  'admin2': 'Provincia de Talca',
  'cc': 'CL'},
 {'lat': '-3.35167',
  'lon': '128.36853',
  'name': 'Kairatu',
  'admin1': 'Maluku',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-21.15216',
  'lon': '-175.21333',
  'name': 'Haveluloto',
  'admin1': 'Tongatapu',
  'admin2': '',
  'cc': 'TO'},
 {'lat': '-54.28111',
  'lon': '-36.5092',
  'name': 'Grytviken',
  'admin1': '',
  'admin2': '',
  'cc': 'GS'},
 {'lat': '-6.8092',
  'lon': '105.6292',
  'name': 'Tugu Hilir',
  'admin1': 'Banten',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-33.59473',
  'lon': '-71.60746',
  'name': 'San Antonio',
  'admin1': 'Valparaiso',
  'admin2': 'San Antonio Province',
  'cc': 'CL'},
 {'lat': '-16.09992',
  'lon': '167.41636',
  'name': 'Lakatoro',
  'admin1': 'Malampa',
  'admin2': '',
  'cc': 'VU'},
 {'lat': '-0.62546',
  'lon': '127.47808',
  'name': 'Labuha',
  'admin1': 'Maluku Utara',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-17.95538',
  'lon': '122.23922',
  'name': 'Broome',
  'admin1': 'Western Australia',
  'admin2': 'Broome',
  'cc': 'AU'},
 {'lat': '0.76202',
  'lon': '127.32015',
  'name': 'Jambulang',
  'admin1': 'Maluku Utara',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '35.62246',
  'lon': '-117.6709',
  'name': 'Ridgecrest',
  'admin1': 'California',
  'admin2': 'Kern County',
  'cc': 'US'},
 {'lat': '-3.72525',
  'lon': '128.1471',
  'name': 'Amahusu',
  'admin1': 'Maluku',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-21.33333',
  'lon': '-174.95',
  'name': '`Ohonua',
  'admin1': "'Eua",
  'admin2': '',
  'cc': 'TO'},
 {'lat': '13.48833',
  'lon': '-89.32222',
  'name': 'La Libertad',
  'admin1': 'La Libertad',
  'admin2': '',
  'cc': 'SV'},
 {'lat': '-5.55',
  'lon': '-75.8',
  'name': 'Santa Cruz',
  'admin1': 'Loreto',
  'admin2': 'Provincia de Alto Amazonas',
  'cc': 'PE'},
 {'lat': '-4.19671',
  'lon': '152.17215',
  'name': 'Rabaul',
  'admin1': 'East New Britain',
  'admin2': '',
  'cc': 'PG'},
 {'lat': '-7.19955',
  'lon': '146.64555',
  'name': 'Bulolo',
  'admin1': 'Morobe',
  'admin2': 'Bulolo',
  'cc': 'PG'},
 {'lat': '-0.9516',
  'lon': '122.7875',
  'name': 'Luwuk',
  'admin1': 'Central Sulawesi',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-54.28111',
  'lon': '-36.5092',
  'name': 'Grytviken',
  'admin1': '',
  'admin2': '',
  'cc': 'GS'},
 {'lat': '-14.90843',
  'lon': '-70.19616',
  'name': 'Azangaro',
  'admin1': 'Puno',
  'admin2': 'Provincia de Azangaro',
  'cc': 'PE'},
 {'lat': '-2.04934',
  'lon': '-77.00856',
  'name': 'Montalvo',
  'admin1': 'Pastaza',
  'admin2': 'Canton Pastaza',
  'cc': 'EC'},
 {'lat': '14.72076',
  'lon': '-92.42146',
  'name': 'Puerto Madero',
  'admin1': 'Chiapas',
  'admin2': '',
  'cc': 'MX'},
 {'lat': '-30.8636',
  'lon': '30.37052',
  'name': 'Margate',
  'admin1': 'KwaZulu-Natal',
  'admin2': 'Ugu District Municipality',
  'cc': 'ZA'},
 {'lat': '-29.95332',
  'lon': '-71.33947',
  'name': 'Coquimbo',
  'admin1': 'Coquimbo',
  'admin2': 'Provincia de Elqui',
  'cc': 'CL'},
 {'lat': '-13.88333',
  'lon': '167.55',
  'name': 'Sola',
  'admin1': 'Torba',
  'admin2': '',
  'cc': 'VU'},
 {'lat': '1.49305',
  'lon': '127.55149',
  'name': 'Tongutisungi',
  'admin1': 'Maluku Utara',
  'admin2': '',
  'cc': 'ID'},
 {'lat': '-8.16139',
  'lon': '-70.76556',
  'name': 'Tarauaca',
  'admin1': 'Acre',
  'admin2': 'Tarauaca',
  'cc': 'BR'},
 {'lat': '6.36115',
  'lon': '126.17778',
  'name': 'Pondaguitan',
  'admin1': 'Davao',
  'admin2': 'Province of Davao Oriental',
  'cc': 'PH'},
 {'lat': '56.22778',
  'lon': '162.47778',
  'name': "Ust'-Kamchatsk Staryy",
  'admin1': 'Kamtsjatka',
  'admin2': '',
  'cc': 'RU'},
 {'lat': '-54.28111',
  'lon': '-36.5092',
  'name': 'Grytviken',
  'admin1': '',
  'admin2': '',
  'cc': 'GS'},
 {'lat': '-21.55',
  'lon': '167.88333',
  'name': 'Tadine',
  'admin1': 'Loyalty Islands',
  'admin2': 'Mare',
  'cc': 'NC'},
 {'lat': '-21.55',
  'lon': '167.88333',
  'name': 'Tadine',
  'admin1': 'Loyalty Islands',
  'admin2': 'Mare',
  'cc': 'NC'},
 {'lat': '61.21806',
  'lon': '-149.90028',
  'name': 'Anchorage',
  'admin1': 'Alaska',
  'admin2': 'Anchorage Municipality',
  'cc': 'US'},
 {'lat': '-14.31096',
  'lon': '-178.11094',
  'name': 'Alo',
  'admin1': "Circonscription d'Alo",
  'admin2': '',
  'cc': 'WF'},
 {'lat': '70.9221',
  'lon': '-8.7187',
  'name': 'Olonkinbyen',
  'admin1': 'Jan Mayen',
  'admin2': 'Jan Mayen',
  'cc': 'SJ'},
 {'lat': '37.71935',
  'lon': '20.83013',
  'name': 'Lithakia',
  'admin1': 'Ionian Islands',
  'admin2': 'Nomos Zakynthou',
  'cc': 'GR'},
 {'lat': '49.15314',
  'lon': '-125.90744',
  'name': 'Tofino',
  'admin1': 'British Columbia',
  'admin2': 'Regional District of Alberni-Clayoquot',
  'cc': 'CA'},
 {'lat': '49.15314',
  'lon': '-125.90744',
  'name': 'Tofino',
  'admin1': 'British Columbia',
  'admin2': 'Regional District of Alberni-Clayoquot',
  'cc': 'CA'},
 {'lat': '49.15314',
  'lon': '-125.90744',
  'name': 'Tofino',
  'admin1': 'British Columbia',
  'admin2': 'Regional District of Alberni-Clayoquot',
  'cc': 'CA'},
 {'lat': '-21.55',
  'lon': '167.88333',
  'name': 'Tadine',
  'admin1': 'Loyalty Islands',
  'admin2': 'Mare',
  'cc': 'NC'},
 {'lat': '51.49604',
  'lon': '156.50102',
  'name': 'Ozernovskiy',
  'admin1': 'Kamtsjatka',

In [194]:
df['Country_Code'] = [r['cc'] for r in results]

In [195]:
import pycountry

def code_to_country(code):
    try:
        return pycountry.countries.get(alpha_2=code).name
    except:
        return None

df['Country'] = df['Country_Code'].apply(code_to_country)

In [196]:
!pip install pycountry

Requirement already satisfied: pycountry in e:\anaconda hehehe\lib\site-packages (24.6.1)

In [197]:
df

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,...,gap,magType,depth,latitude,longitude,location,continent,country,Country_Code,Country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,1,1,768,us,117,...,17.0,mww,14.000,-9.7963,159.596,"Malango, Solomon Islands",Oceania,Solomon Islands,SB,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,18-11-2022 13:37,4,4,1,0,735,us,99,...,34.0,mww,25.000,-4.9559,100.738,"Bengkulu, Indonesia",NaN,NaN,ID,Indonesia
2,M 7.0 -,7.0,12-11-2022 07:09,3,3,1,1,755,us,147,...,18.0,mww,579.000,-20.0508,-178.346,NaN,Oceania,Fiji,TO,Tonga
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,11-11-2022 10:48,5,5,1,1,833,us,149,...,21.0,mww,37.000,-19.2918,-172.129,"Neiafu, Tonga",NaN,NaN,TO,Tonga
4,M 6.6 -,6.6,09-11-2022 10:14,0,2,1,1,670,us,131,...,27.0,mww,624.464,-25.5948,178.278,NaN,NaN,NaN,FJ,Fiji
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,"M 7.7 - 28 km SSW of Puerto El Triunfo, El Sal...",7.7,13-01-2001 17:33,0,8,0,0,912,us,427,...,0.0,mwc,60.000,13.0490,-88.660,"Puerto El Triunfo, El Salvador",NaN,NaN,SV,El Salvador
778,"M 6.9 - 47 km S of Old Harbor, Alaska",6.9,10-01-2001 16:02,5,7,0,0,745,ak,0,...,0.0,mw,36.400,56.7744,-153.281,"Old Harbor, Alaska",North America,NaN,US,United States
779,"M 7.1 - 16 km NE of Port-Olry, Vanuatu",7.1,09-01-2001 16:49,0,7,0,0,776,us,372,...,0.0,mwb,103.000,-14.9280,167.170,"Port-Olry, Vanuatu",NaN,Vanuatu,VU,Vanuatu
780,"M 6.8 - Mindanao, Philippines",6.8,01-01-2001 08:54,0,5,0,0,711,us,64,...,0.0,mwc,33.000,6.6310,126.899,"Mindanao, Philippines",NaN,NaN,PH,Philippines
781,"M 7.5 - 21 km SE of Lukatan, Philippines",7.5,01-01-2001 06:57,0,7,0,0,865,us,324,...,0.0,mwc,33.000,6.8980,126.579,"Lukatan, Philippines",NaN,Philippines,PH,Philippines

In [198]:
df.drop('country', axis=1  , inplace=True)

In [199]:
df

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,Country_Code,Country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,22-11-2022 02:03,8,7,1,1,768,us,117,0.509,17.0,mww,14.000,-9.7963,159.596,"Malango, Solomon Islands",Oceania,SB,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,18-11-2022 13:37,4,4,1,0,735,us,99,2.229,34.0,mww,25.000,-4.9559,100.738,"Bengkulu, Indonesia",NaN,ID,Indonesia
2,M 7.0 -,7.0,12-11-2022 07:09,3,3,1,1,755,us,147,3.125,18.0,mww,579.000,-20.0508,-178.346,NaN,Oceania,TO,Tonga
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,11-11-2022 10:48,5,5,1,1,833,us,149,1.865,21.0,mww,37.000,-19.2918,-172.129,"Neiafu, Tonga",NaN,TO,Tonga
4,M 6.6 -,6.6,09-11-2022 10:14,0,2,1,1,670,us,131,4.998,27.0,mww,624.464,-25.5948,178.278,NaN,NaN,FJ,Fiji
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,"M 7.7 - 28 km SSW of Puerto El Triunfo, El Sal...",7.7,13-01-2001 17:33,0,8,0,0,912,us,427,0.000,0.0,mwc,60.000,13.0490,-88.660,"Puerto El Triunfo, El Salvador",NaN,SV,El Salvador
778,"M 6.9 - 47 km S of Old Harbor, Alaska",6.9,10-01-2001 16:02,5,7,0,0,745,ak,0,0.000,0.0,mw,36.400,56.7744,-153.281,"Old Harbor, Alaska",North America,US,United States
779,"M 7.1 - 16 km NE of Port-Olry, Vanuatu",7.1,09-01-2001 16:49,0,7,0,0,776,us,372,0.000,0.0,mwb,103.000,-14.9280,167.170,"Port-Olry, Vanuatu",NaN,VU,Vanuatu
780,"M 6.8 - Mindanao, Philippines",6.8,01-01-2001 08:54,0,5,0,0,711,us,64,0.000,0.0,mwc,33.000,6.6310,126.899,"Mindanao, Philippines",NaN,PH,Philippines
781,"M 7.5 - 21 km SE of Lukatan, Philippines",7.5,01-01-2001 06:57,0,7,0,0,865,us,324,0.000,0.0,mwc,33.000,6.8980,126.579,"Lukatan, Philippines",NaN,PH,Philippines

In [200]:
df.drop(columns=['date_time' , 'Country_Code' ] , axis=1 , inplace=True)

In [201]:
df

,title,magnitude,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,Country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,8,7,1,1,768,us,117,0.509,17.0,mww,14.000,-9.7963,159.596,"Malango, Solomon Islands",Oceania,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,4,4,1,0,735,us,99,2.229,34.0,mww,25.000,-4.9559,100.738,"Bengkulu, Indonesia",NaN,Indonesia
2,M 7.0 -,7.0,3,3,1,1,755,us,147,3.125,18.0,mww,579.000,-20.0508,-178.346,NaN,Oceania,Tonga
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,5,5,1,1,833,us,149,1.865,21.0,mww,37.000,-19.2918,-172.129,"Neiafu, Tonga",NaN,Tonga
4,M 6.6 -,6.6,0,2,1,1,670,us,131,4.998,27.0,mww,624.464,-25.5948,178.278,NaN,NaN,Fiji
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,"M 7.7 - 28 km SSW of Puerto El Triunfo, El Sal...",7.7,0,8,0,0,912,us,427,0.000,0.0,mwc,60.000,13.0490,-88.660,"Puerto El Triunfo, El Salvador",NaN,El Salvador
778,"M 6.9 - 47 km S of Old Harbor, Alaska",6.9,5,7,0,0,745,ak,0,0.000,0.0,mw,36.400,56.7744,-153.281,"Old Harbor, Alaska",North America,United States
779,"M 7.1 - 16 km NE of Port-Olry, Vanuatu",7.1,0,7,0,0,776,us,372,0.000,0.0,mwb,103.000,-14.9280,167.170,"Port-Olry, Vanuatu",NaN,Vanuatu
780,"M 6.8 - Mindanao, Philippines",6.8,0,5,0,0,711,us,64,0.000,0.0,mwc,33.000,6.6310,126.899,"Mindanao, Philippines",NaN,Philippines
781,"M 7.5 - 21 km SE of Lukatan, Philippines",7.5,0,7,0,0,865,us,324,0.000,0.0,mwc,33.000,6.8980,126.579,"Lukatan, Philippines",NaN,Philippines

In [202]:
df['net'].unique()

array(['us', 'at', 'pt', 'ak', 'nn', 'ci', 'hv', 'nc', 'official',
       'duputel', 'uw'], dtype=object)

In [203]:
df['net'].value_counts()

net
us          747
ak           11
official      8
nc            3
duputel       3
at            2
pt            2
ci            2
hv            2
nn            1
uw            1
Name: count, dtype: int64

In [204]:
df.drop(columns=['net'], inplace=True)

In [205]:
df['magType'].unique()

array(['mww', 'mwb', 'Mi', 'ml', 'mw', 'mwc', 'ms', 'mb', 'md'],
      dtype=object)

In [206]:
df['magType'].value_counts().sum()

782

In [207]:
df['magType'] = df['magType'].fillna('unknown')

In [208]:
df

,title,magnitude,cdi,mmi,alert,tsunami,sig,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,Country
0,"M 7.0 - 18 km SW of Malango, Solomon Islands",7.0,8,7,1,1,768,117,0.509,17.0,mww,14.000,-9.7963,159.596,"Malango, Solomon Islands",Oceania,Solomon Islands
1,"M 6.9 - 204 km SW of Bengkulu, Indonesia",6.9,4,4,1,0,735,99,2.229,34.0,mww,25.000,-4.9559,100.738,"Bengkulu, Indonesia",NaN,Indonesia
2,M 7.0 -,7.0,3,3,1,1,755,147,3.125,18.0,mww,579.000,-20.0508,-178.346,NaN,Oceania,Tonga
3,"M 7.3 - 205 km ESE of Neiafu, Tonga",7.3,5,5,1,1,833,149,1.865,21.0,mww,37.000,-19.2918,-172.129,"Neiafu, Tonga",NaN,Tonga
4,M 6.6 -,6.6,0,2,1,1,670,131,4.998,27.0,mww,624.464,-25.5948,178.278,NaN,NaN,Fiji
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,"M 7.7 - 28 km SSW of Puerto El Triunfo, El Sal...",7.7,0,8,0,0,912,427,0.000,0.0,mwc,60.000,13.0490,-88.660,"Puerto El Triunfo, El Salvador",NaN,El Salvador
778,"M 6.9 - 47 km S of Old Harbor, Alaska",6.9,5,7,0,0,745,0,0.000,0.0,mw,36.400,56.7744,-153.281,"Old Harbor, Alaska",North America,United States
779,"M 7.1 - 16 km NE of Port-Olry, Vanuatu",7.1,0,7,0,0,776,372,0.000,0.0,mwb,103.000,-14.9280,167.170,"Port-Olry, Vanuatu",NaN,Vanuatu
780,"M 6.8 - Mindanao, Philippines",6.8,0,5,0,0,711,64,0.000,0.0,mwc,33.000,6.6310,126.899,"Mindanao, Philippines",NaN,Philippines
781,"M 7.5 - 21 km SE of Lukatan, Philippines",7.5,0,7,0,0,865,324,0.000,0.0,mwc,33.000,6.8980,126.579,"Lukatan, Philippines",NaN,Philippines

In [209]:
df.drop(columns=['magType'], inplace=True)

In [210]:
df.drop(columns=['title' , 'continent'], inplace=True)

In [211]:
df

,magnitude,cdi,mmi,alert,tsunami,sig,nst,dmin,gap,depth,latitude,longitude,location,Country
0,7.0,8,7,1,1,768,117,0.509,17.0,14.000,-9.7963,159.596,"Malango, Solomon Islands",Solomon Islands
1,6.9,4,4,1,0,735,99,2.229,34.0,25.000,-4.9559,100.738,"Bengkulu, Indonesia",Indonesia
2,7.0,3,3,1,1,755,147,3.125,18.0,579.000,-20.0508,-178.346,NaN,Tonga
3,7.3,5,5,1,1,833,149,1.865,21.0,37.000,-19.2918,-172.129,"Neiafu, Tonga",Tonga
4,6.6,0,2,1,1,670,131,4.998,27.0,624.464,-25.5948,178.278,NaN,Fiji
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,7.7,0,8,0,0,912,427,0.000,0.0,60.000,13.0490,-88.660,"Puerto El Triunfo, El Salvador",El Salvador
778,6.9,5,7,0,0,745,0,0.000,0.0,36.400,56.7744,-153.281,"Old Harbor, Alaska",United States
779,7.1,0,7,0,0,776,372,0.000,0.0,103.000,-14.9280,167.170,"Port-Olry, Vanuatu",Vanuatu
780,6.8,0,5,0,0,711,64,0.000,0.0,33.000,6.6310,126.899,"Mindanao, Philippines",Philippines
781,7.5,0,7,0,0,865,324,0.000,0.0,33.000,6.8980,126.579,"Lukatan, Philippines",Philippines

In [212]:
df.drop(columns=['location'], inplace=True)

In [213]:
df

,magnitude,cdi,mmi,alert,tsunami,sig,nst,dmin,gap,depth,latitude,longitude,Country
0,7.0,8,7,1,1,768,117,0.509,17.0,14.000,-9.7963,159.596,Solomon Islands
1,6.9,4,4,1,0,735,99,2.229,34.0,25.000,-4.9559,100.738,Indonesia
2,7.0,3,3,1,1,755,147,3.125,18.0,579.000,-20.0508,-178.346,Tonga
3,7.3,5,5,1,1,833,149,1.865,21.0,37.000,-19.2918,-172.129,Tonga
4,6.6,0,2,1,1,670,131,4.998,27.0,624.464,-25.5948,178.278,Fiji
...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,7.7,0,8,0,0,912,427,0.000,0.0,60.000,13.0490,-88.660,El Salvador
778,6.9,5,7,0,0,745,0,0.000,0.0,36.400,56.7744,-153.281,United States
779,7.1,0,7,0,0,776,372,0.000,0.0,103.000,-14.9280,167.170,Vanuatu
780,6.8,0,5,0,0,711,64,0.000,0.0,33.000,6.6310,126.899,Philippines
781,7.5,0,7,0,0,865,324,0.000,0.0,33.000,6.8980,126.579,Philippines

In [214]:
df['Country'].nunique()

67

In [215]:
freq = df['Country'].value_counts(normalize=True)
df['Country_freq'] = df['Country'].map(freq)

df.drop(columns=['Country'], inplace=True)

In [216]:
df

,magnitude,cdi,mmi,alert,tsunami,sig,nst,dmin,gap,depth,latitude,longitude,Country_freq
0,7.0,8,7,1,1,768,117,0.509,17.0,14.000,-9.7963,159.596,0.049872
1,6.9,4,4,1,0,735,99,2.229,34.0,25.000,-4.9559,100.738,0.154731
2,7.0,3,3,1,1,755,147,3.125,18.0,579.000,-20.0508,-178.346,0.046036
3,7.3,5,5,1,1,833,149,1.865,21.0,37.000,-19.2918,-172.129,0.046036
4,6.6,0,2,1,1,670,131,4.998,27.0,624.464,-25.5948,178.278,0.012788
...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,7.7,0,8,0,0,912,427,0.000,0.0,60.000,13.0490,-88.660,0.007673
778,6.9,5,7,0,0,745,0,0.000,0.0,36.400,56.7744,-153.281,0.047315
779,7.1,0,7,0,0,776,372,0.000,0.0,103.000,-14.9280,167.170,0.053708
780,6.8,0,5,0,0,711,64,0.000,0.0,33.000,6.6310,126.899,0.030691
781,7.5,0,7,0,0,865,324,0.000,0.0,33.000,6.8980,126.579,0.030691

In [217]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [218]:
X = df.drop('magnitude' , axis=1)
y = df['magnitude']

In [219]:
X = r.fit_transform(X)

In [220]:
X_train , X_test , y_train,y_test = train_test_split(X,y,test_size=0.20 , random_state=1)

In [221]:
X_train.shape , X_test.shape

((625, 12), (157, 12))

In [222]:
# Base Model 
linear = LinearRegression()

In [223]:
linear.fit(X_train,y_train)

LinearRegression()

In [224]:
linear_pred = linear.predict(X_test)

In [225]:
r2_score(y_test , linear_pred)

0.21734378998027482

In [226]:
tree = RandomForestRegressor()

In [227]:
tree.fit(X_train,y_train)
pred = tree.predict(X_test)

In [228]:
r2_score(y_test,pred)

0.7140334910044299

In [229]:
svr = SVR(kernel='linear')
svr.fit(X_train,y_train)
pred_svr = svr.predict(X_test)

In [230]:
r2_score(y_test ,pred_svr)

0.26418032471743313

In [231]:
from sklearn.model_selection import GridSearchCV

In [240]:
params = param_grid = {
    'n_estimators': [200, 300, 500],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'max_features': ['sqrt', 'log2', 0.5]
}

In [241]:
gird = GridSearchCV(tree ,cv=5 , scoring='r2' ,param_grid= params , verbose=2 )

In [ ]:
gird.fit(X_train,y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=300; total time=   0.3s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=200; total time=   0.5s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=200; total time=   0.5s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=200; total time=   0.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=300; total time=   0.8s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=300; total time=   0.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=300; total time=   0.7s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=300; total time=   0.6s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=300; total time=   0.5s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   0.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   0.8s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   1.1s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   0.8s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   0.8s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=200; total time=   0.3s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=200; total time=   0.3s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=200; total time=   0.3s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=200; total time=   0.3s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=200; total time=   0.3s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=300; total time=   0.5s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=300; total time=   0.5s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   1.2s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   0.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   0.8s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   0.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   0.8s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=200; total time=   0.8s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=200; total time=   0.6s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=200; total time=   0.6s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=300; total time=   0.6s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=300; total time=   0.5s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=300; total time=   0.5s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=300; total time=   0.5s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=300; total time=   0.6s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=500; total time=   1.1s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=500; total time=   1.2s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=500; total time=   1.2s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=500; total time=   1.0s
[CV] END max_depth=10, max_features=log2, min_samples_split=2, n_estimators=500; total time=   0.9s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=300; total time=   0.6s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=300; total time=   0.5s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=500; total time=   0.9s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=500; total time=   0.9s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=500; total time=   1.0s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=500; total time=   0.9s
[CV] END max_depth=10, max_features=log2, min_samples_split=5, n_estimators=500; total time=   0.9s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=200; total time=   0.3s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=300; total time=   0.4s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=300; total time=   0.3s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=300; total time=   0.3s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=500; total time=   0.6s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=500; total time=   0.8s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=500; total time=   0.9s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=500; total time=   1.0s
[CV] END max_depth=10, max_features=log2, min_samples_split=10, n_estimators=500; total time=   1.2s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=200; total time=   0.5s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=200; total time=   0.5s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=300; total time=   0.6s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=300; total time=   0.6s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=300; total time=   0.7s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=300; total time=   0.8s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=300; total time=   0.7s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=500; total time=   1.4s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=500; total time=   1.5s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=500; total time=   1.3s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=500; total time=   1.2s
[CV] END max_depth=10, max_features=0.5, min_samples_split=2, n_estimators=500; total time=   1.6s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=200; total time=   0.5s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=200; total time=   0.5s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=300; total time=   0.7s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=300; total time=   0.8s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=300; total time=   0.8s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=300; total time=   0.7s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=300; total time=   0.8s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=500; total time=   1.2s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=500; total time=   1.2s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=500; total time=   1.4s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=500; total time=   1.3s
[CV] END max_depth=10, max_features=0.5, min_samples_split=5, n_estimators=500; total time=   1.7s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=200; total time=   0.4s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=200; total time=   0.6s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=200; total time=   0.6s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=200; total time=   0.6s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=300; total time=   0.7s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=300; total time=   0.6s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=300; total time=   0.5s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=300; total time=   0.5s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=300; total time=   0.5s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=500; total time=   0.9s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=500; total time=   0.8s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=500; total time=   0.7s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=500; total time=   0.7s
[CV] END max_depth=10, max_features=0.5, min_samples_split=10, n_estimators=500; total time=   0.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=300; total time=   0.5s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   1.0s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.8s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=2, n_estimators=500; total time=   0.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   0.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   0.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   0.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   0.8s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=5, n_estimators=500; total time=   0.7s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=300; total time=   0.3s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=300; total time=   0.3s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=300; total time=   0.3s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=300; total time=   0.3s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   0.8s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   0.6s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   0.6s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   0.6s
[CV] END max_depth=20, max_features=sqrt, min_samples_split=10, n_estimators=500; total time=   0.6s
[CV] END max_depth=20, max_features=log2, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=log2, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=log2, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=log2, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=log2, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END max_depth=20, max_features=log2, min_samples_split=2, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=log2, min_samples_split=2, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=log2, min_samples_split=2, n_estimators=300; total time=   0.4s
[CV] END max_depth=20, max_features=log2, min_samples_split=2, n_estimators=300; total time=   0.4s